### ISSUE TITLE
Built from Source: Stops Tree Loading

### ISSUE THREAD

**Issue by Pop000100** [ontrigger/ValheimPerformanceOptimizations#39] opened 2023-03-27 19:51 UTC
First of all, if you know and don't want any feedback on the unreleased version tell me ill close this issue and ill leave you alone.
with that out of the way my issue is: 
Stops trees from loading after running far away from start of session. they sometimes pop in.

I appreciated this mod, glad to see some work on it.

**Comment by ontrigger** [comment] 2023-03-27 20:18
Can you try this version? The github commits are outdated
https://cdn.discordapp.com/attachments/1085880046956335145/1088015731347689472/vpo-1.0.0-a3.zip

**Comment by ontrigger** [comment] 2023-03-27 20:27
Do note that this is for the latest ptb only

**Comment by Pop000100** [comment] 2023-03-28 04:51
did you actually optimize the standard unity libraries as well, I added the included ones as refs didn't know the changes

**Comment by ontrigger** [comment] 2023-03-28 11:14
The libs in the data folder were not in the game by default, so I had to include them in the dl. On a related note, I might have forgotten to update said libs to the new unity version, which is why you're probably getting the ctd and I'm not (I replaced all the dlls in my folder with unity ones)

**Comment by ontrigger** [comment] 2023-03-28 12:56
> Test: that causes CTD [LogOutput.log](https://github.com/ontrigger/ValheimPerformanceOptimizations/files/11085509/LogOutput.log)

This kind of looks like a bepinex problem. Here's someone reporting the exact same issue with V+: https://github.com/valheimPlus/ValheimPlus/issues/800 
The new update caused a shitload of issues with the preloader, forcing the community to update the pack to a new version. 

https://cdn.discordapp.com/attachments/826573164371902467/1088128708285583391/denikson-BepInExPack_Valheim-5.4.2101.zip

I've also just checked the libs and it seems like they do not need to be updated

**Comment by Pop000100** [comment] 2023-03-28 19:02
updating BepInEx fixes the CTD but trees are still not loading.
This is what it looks like
![bug](https://user-images.githubusercontent.com/20156032/228340786-09163cbb-9871-4721-ad3f-fd7b6c5323e6.png)
Reloading works
![reload](https://user-images.githubusercontent.com/20156032/228340834-fa7f3107-4bf7-4679-9b94-70173401322d.png)
This is a log when I encounter it
[LogOutput.log](https://github.com/ontrigger/ValheimPerformanceOptimizations/files/11093292/LogOutput.log)

**Comment by ontrigger** [comment] 2023-03-28 20:16
Was able to reproduce. It seems like distant objects don't want to be spawned in a near area.

**Comment by Pop000100** [comment] 2023-03-28 20:57
Good, Now that the update dropped I can disable the public test right? Or are you always going to be targeting that?

**Comment by ontrigger** [comment] 2023-03-28 21:06
I will always target the latest patch, but you should be fine on main for now as it is identical to ptb.
I'll be able to fix it tomorrow; looks like a simple oversight from what I understand

**Comment by Pop000100** [comment] 2023-03-28 22:19
Even if it has unstability?

**Comment by ontrigger** [comment] 2023-03-29 23:17
Should be fixed now. Here's the test version 
[vpo-1.0.0-a4.zip](https://github.com/ontrigger/ValheimPerformanceOptimizations/files/11106328/vpo-1.0.0-a4.zip)

> Even if it has unstability?
So what if it's unstable? You can always use a previous version of VPO that is compatible with a PTB as every update on the test branch will eventually become stable anyway. The latest version targets the latest ptb yet is fully compatible with the stable branch.

**Closed** 2023-03-30 15:36 UTC
