### ISSUE TITLE
ValheimPerformanceOptimizations breaks the bepinex config manager

### ISSUE THREAD

**Issue by h587728** [ontrigger/ValheimPerformanceOptimizations#27] opened 2021-09-21 11:05 UTC
Just title. While this mod is installed the bepinex config manager is empty. Uninstalling this mod resolves the issue.

**Comment by MSchmoecker** [comment] 2021-09-26 07:30
This bug was fixed in 0.7.5. It was caused by an error at startup time.

**Closed by MSchmoecker** 2021-09-26 07:30 UTC
